/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminBV } from "./AdminBV";
export type { AlumnaiPOAP } from "./AlumnaiPOAP";
export type { ERC20 } from "./ERC20";
export type { Multicall2 } from "./Multicall2";
export type { NewBiePOAP } from "./NewBiePOAP";
export type { POAPUpgrade } from "./POAPUpgrade";
export type { SeniorPOAP } from "./SeniorPOAP";
export type { WelcomePOAP } from "./WelcomePOAP";
export * as factories from "./factories";
export { AdminBV__factory } from "./factories/AdminBV__factory";
export { AlumnaiPOAP__factory } from "./factories/AlumnaiPOAP__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { Multicall2__factory } from "./factories/Multicall2__factory";
export { NewBiePOAP__factory } from "./factories/NewBiePOAP__factory";
export { POAPUpgrade__factory } from "./factories/POAPUpgrade__factory";
export { SeniorPOAP__factory } from "./factories/SeniorPOAP__factory";
export { WelcomePOAP__factory } from "./factories/WelcomePOAP__factory";
