/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { AdminBV, AdminBVInterface } from "../AdminBV";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "admins",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "point",
        type: "uint256",
      },
      {
        internalType: "enum AdminBV.POAPType",
        name: "poapType",
        type: "uint8",
      },
    ],
    name: "decreasePoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "point",
        type: "uint256",
      },
      {
        internalType: "enum AdminBV.POAPType",
        name: "poapType",
        type: "uint8",
      },
    ],
    name: "increasePoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "poaps",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "removeAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
      {
        internalType: "enum AdminBV.POAPType",
        name: "poapType",
        type: "uint8",
      },
    ],
    name: "removeMember",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "ps",
        type: "address[]",
      },
    ],
    name: "setPOAP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AdminBV__factory {
  static readonly abi = _abi;
  static createInterface(): AdminBVInterface {
    return new Interface(_abi) as AdminBVInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AdminBV {
    return new Contract(address, _abi, runner) as unknown as AdminBV;
  }
}
