/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Attendance, AttendanceInterface } from "../Attendance";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract AdminBV",
        name: "_admin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "contract AdminBV",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum AdminBV.POAPType",
        name: "_type",
        type: "uint8",
      },
    ],
    name: "attend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "attended",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lock",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lockCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unlockCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Attendance__factory {
  static readonly abi = _abi;
  static createInterface(): AttendanceInterface {
    return new Interface(_abi) as AttendanceInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Attendance {
    return new Contract(address, _abi, runner) as unknown as Attendance;
  }
}
