/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Attendance3th, Attendance3thInterface } from "../Attendance3th";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract AdminBV",
        name: "_admin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "contract AdminBV",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isFirst",
        type: "bool",
      },
    ],
    name: "attend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "attended",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lock",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lockCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unlockCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Attendance3th__factory {
  static readonly abi = _abi;
  static createInterface(): Attendance3thInterface {
    return new Interface(_abi) as Attendance3thInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Attendance3th {
    return new Contract(address, _abi, runner) as unknown as Attendance3th;
  }
}
