/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdminBV__factory } from "./AdminBV__factory";
export { AlumnaiPOAP__factory } from "./AlumnaiPOAP__factory";
export { Attendance3th__factory } from "./Attendance3th__factory";
export { ERC20__factory } from "./ERC20__factory";
export { Multicall2__factory } from "./Multicall2__factory";
export { NewBiePOAP__factory } from "./NewBiePOAP__factory";
export { POAPUpgrade__factory } from "./POAPUpgrade__factory";
export { SeniorPOAP__factory } from "./SeniorPOAP__factory";
export { WelcomePOAP__factory } from "./WelcomePOAP__factory";
