/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { POAPUpgrade, POAPUpgradeInterface } from "../POAPUpgrade";

const _abi = [
  {
    inputs: [],
    name: "upgradeGrade",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class POAPUpgrade__factory {
  static readonly abi = _abi;
  static createInterface(): POAPUpgradeInterface {
    return new Interface(_abi) as POAPUpgradeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): POAPUpgrade {
    return new Contract(address, _abi, runner) as unknown as POAPUpgrade;
  }
}
